{{- if .Values.console.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dws.console.fullname" . }}
  namespace: {{ include "dws.namespace" . }}
  labels:
    {{- include "dws.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
spec:
  selector:
    {{- include "dws.console.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.console.service.port }}
      targetPort: http
{{- end }}
