{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dws.postgres.fullname" . }}
  namespace: {{ include "dws.namespace" . }}
  labels:
    {{- include "dws.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  username: {{ .Values.postgresql.auth.username | quote }}
  password: {{ .Values.postgresql.auth.password | quote }}
  database: {{ .Values.postgresql.auth.database | quote }}
  database-url: {{ printf "postgres://%s:%s@%s.%s.svc.cluster.local:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "dws.postgres.fullname" .) (include "dws.namespace" .) .Values.postgresql.auth.database | quote }}
{{- end }}
