{{- include "dws.adminGateway.validate" . -}}
{{- if .Values.adminGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dws.adminGateway.fullname" . }}
  namespace: {{ include "dws.namespace" . }}
  labels:
    {{- include "dws.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin-gateway
spec:
  type: {{ .Values.adminGateway.service.type }}
  selector:
    {{- include "dws.adminGateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.adminGateway.service.port }}
      targetPort: http
{{- end }}
