/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstancesIndexRouteImport } from './routes/instances/index'
import { Route as InstancesIdRouteImport } from './routes/instances/$id'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as WorkflowsNameRouteImport } from './routes/workflows/$name'
import { Route as WorkflowsNewRouteImport } from './routes/workflows/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesIndexRoute = InstancesIndexRouteImport.update({
  id: '/instances/',
  path: '/instances/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesIdRoute = InstancesIdRouteImport.update({
  id: '/instances/$id',
  path: '/instances/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsNameRoute = WorkflowsNameRouteImport.update({
  id: '/workflows/$name',
  path: '/workflows/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsNewRoute = WorkflowsNewRouteImport.update({
  id: '/workflows/new',
  path: '/workflows/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/instances/$id': typeof InstancesIdRoute
  '/workflows/$name': typeof WorkflowsNameRoute
  '/workflows/new': typeof WorkflowsNewRoute
  '/instances/': typeof InstancesIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instances/$id': typeof InstancesIdRoute
  '/workflows/$name': typeof WorkflowsNameRoute
  '/workflows/new': typeof WorkflowsNewRoute
  '/instances': typeof InstancesIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/instances/$id': typeof InstancesIdRoute
  '/workflows/$name': typeof WorkflowsNameRoute
  '/workflows/new': typeof WorkflowsNewRoute
  '/instances/': typeof InstancesIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/instances/$id'
    | '/workflows/$name'
    | '/workflows/new'
    | '/instances/'
    | '/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/instances/$id'
    | '/workflows/$name'
    | '/workflows/new'
    | '/instances'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/instances/$id'
    | '/workflows/$name'
    | '/workflows/new'
    | '/instances/'
    | '/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstancesIdRoute: typeof InstancesIdRoute
  WorkflowsNameRoute: typeof WorkflowsNameRoute
  WorkflowsNewRoute: typeof WorkflowsNewRoute
  InstancesIndexRoute: typeof InstancesIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances/': {
      id: '/instances/'
      path: '/instances'
      fullPath: '/instances/'
      preLoaderRoute: typeof InstancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances/$id': {
      id: '/instances/$id'
      path: '/instances/$id'
      fullPath: '/instances/$id'
      preLoaderRoute: typeof InstancesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$name': {
      id: '/workflows/$name'
      path: '/workflows/$name'
      fullPath: '/workflows/$name'
      preLoaderRoute: typeof WorkflowsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/new': {
      id: '/workflows/new'
      path: '/workflows/new'
      fullPath: '/workflows/new'
      preLoaderRoute: typeof WorkflowsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstancesIdRoute: InstancesIdRoute,
  WorkflowsNameRoute: WorkflowsNameRoute,
  WorkflowsNewRoute: WorkflowsNewRoute,
  InstancesIndexRoute: InstancesIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
