{{- if .Values.dapr.enabled }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: {{ include "dws.namespace" . }}
  labels:
    {{- include "dws.labels" . | nindent 4 }}
    app.kubernetes.io/component: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: {{ include "dws.redis.host" . | quote }}
    - name: redisPassword
      secretKeyRef:
        name: {{ include "dws.redis.secretName" . }}
        key: {{ include "dws.redis.secretKey" . }}
    - name: enableTLS
      value: "false"
auth:
  secretStore: kubernetes
{{- end }}
