{{- if .Values.dex.enabled }}
{{- $password := include "dws.dex.resolvePassword" . }}
{{- if not .Values.dex.adminUser.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dws.dex.adminCredentials.fullname" . }}
  namespace: {{ include "dws.namespace" . }}
  labels:
    {{- include "dws.labels" . | nindent 4 }}
    app.kubernetes.io/component: dex
type: Opaque
stringData:
  email: {{ .Values.dex.adminUser.email | quote }}
  password: {{ $password | quote }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dex.configSecret.name }}
  namespace: {{ include "dws.namespace" . }}
  labels:
    {{- include "dws.labels" . | nindent 4 }}
    app.kubernetes.io/component: dex
type: Opaque
data:
  config.yaml: {{ include "dws.dex.config" (dict "root" . "password" $password) | b64enc | quote }}
{{- end }}
