{{- if and .Values.admin.enabled (not .Values.postgresql.enabled) (not .Values.admin.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dws.admin.fullname" . }}
  namespace: {{ include "dws.namespace" . }}
  labels:
    {{- include "dws.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
type: Opaque
stringData:
  database-url: {{ .Values.admin.database.url | quote }}
{{- end }}
